### ISSUE TITLE
Seed API service with example data

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/rocc-app#23]
## Motivation

This app communicate with the ROCC API service to get list/create/delete challenges, organization and other objects. During the development of the app, we need the API service to contain data so that we can 1) test that the *models* and *services* provided by the library `rocc-client-angular` work and 2) visualize the data in the web client. Using mock data local to the app enables 2) but not 1).

## Discussion

The idea is to perform the following action when the app starts (and restart if the following operation does not take too much time) using the services provided by the library `rocc-client-angular` for the different types of objects.

1. Delete all the data in the API service
2. Seed the API service with example data

This approach was implemented in the project SageBio Collaboration Portal. Note that the solution was implemented at the level of the API service and not the web client.

1. When the API service starts, [this line is executed](https://github.com/Sage-Bionetworks/sagebio-collaboration-portal/blob/b83bb3a2af92e1596724682a642bb78d7bf7e226/server/app.js#L51) if the DB needs to be seeded.
2. The file [seed.js](https://github.com/Sage-Bionetworks/sagebio-collaboration-portal/blob/develop/server/config/seed.js) takes care of emptying the DB and seeding it with new data. Note that these operation are executed using the methods provided by the DB models (e.g. `Article.find({})`) and not using API calls.
3. The folder [seeds](https://github.com/Sage-Bionetworks/sagebio-collaboration-portal/tree/develop/server/config/seeds) contains one folder per "seed profile". The profile "default" was created to seed the DB with the minimum objects required for the app to work. The folder "development" is where we defined example objects so that we can visualize them in the app during development.

For the ROCC app, one question is whether we want to populate the objects from the app or from the API service itself. If the objects to populate are specific to the app, then it makes sense to populate them from the app. For example, the app developer may want to try with a challenge object that has a long title to see if it does not break the app. But local mock data are maybe more suitable for this.

It's worth noting that the app uses live reload to reload whenever we update a file. If seeding from the app takes time, we don't want to seed the API service each time the app reloads. Ideally, the seeding of the API service should only occur if the seed data have changed. One way could be to create an md5 string for the seed data and cache it locally (e.g. in a file), then at the next reload we compare the live md5 with the md5 present in the file. If the two values are different, then we seed the API service, otherwise it's relatively safe to assume that the API service already contains the data we want.

Writing function to seed data from the app is also useful for integration and e2e tests, especially to test that the services provided by the library `rocc-client-angular` work and are well integrated into the app.

Note that seeding from the API service itself has benefits too. For example, we would not have to worry that the app would spend time seeding the API service each time the app restart during development. Also, the seeds could be useful to test other clients, for example the [library client for Python](https://github.com/Sage-Bionetworks/rocc-client-python). But here again, seeding from the client itself (e.g. Python client) is a good way to test that the client works as intended.

## Tasks

Let's try to seed the API service from the app.

- [ ] Review and understand how the seed works in the SageBio Collaboration Portal see above
- [ ] In the app code, identify the best place to run the seed code
- [ ] Implement the seed code
- [ ] If seeding the API service from the app takes too much time (1-2 seconds), consider implementing a caching mechanism so that the app does not seed the API service if the seeds data have not changed (see suggestion above regarding the use of an md5). A simpler solution may be to run the seed only when the app starts, and so if the developer modified the seed data, then we expect him/her stop and restart the app. This approach would makes sense if the seeds data are not changed too frequently, which may be the case. We could start with this approach and if we want a smarter system, then we can use caching.

**Comment by tschaffter** [comment]
@rrchai Let me know if anything is unclear. It would be great if this PR could be completed and merged by our next Monday meeting. We can touch base on Wednesday if you have any questions.
