### ISSUE TITLE
Setup unit and integration tests

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/rocc-app#363]
The following two scripts were added to `package.json` by the Angular CLI when the project has been generated.

- `npm run test`: runs unit and integration tests
- `npm run e2e`: runs end-to-end tests

See [Angular Testing](https://angular.io/guide/testing#testing)

- A unit test file `.spec.ts` is automatically generated by the Angular CLI when creating a new component or service.
- According to the above documentation, it is recommended to group `integration` tests inside a folder called `tests`.
- End-to-end tests have their own dedicated folder called `e2e`. E2E tests are outside the scope of this ticket.

## Task

- [ ] Get one existing unit test to work with `npm run test` (or just `npm test`).
- [ ] Investigate how to use Jest instead of Karma and Jasmine.
- [ ] Identify the pros and cons of both solutions.

**Comment by tschaffter** [comment]
Closing this ticket as we have testing setup in place in the monorepo. e2e tests will be added in the future.
